
server:
  port: 8080
  servlet:
    context-path: /spring-mongo-service
    
spring:
  data:
    mongodb:
      uri: mongodb+srv://amanbansal4244:EUimNgVR7iNY1Fz9@cluster0.eiwu2xo.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: docker-basic-mongo-db
      auto-index-creation: true
        
  
