server:
  port: 8080
  servlet:
    context-path: /spring-mongo-service
    
spring:
  application:
    name: spring-mongo-service
  data:
    mongodb:
      host: '${MONGO_HOST}'
      database: '${MONGO_DB}'
      port: '${MONGO_PORT}'
      username: '${MONGO_USERNAME}'
      password: '${MONGO_PASSWORD}'
  cloud:
    kubernetes:
      discovery:
        register: true
      secrets:
        name: mongo-secret

      config:
        enabled: true
        sources:
          - namespace: default
            name: mongo-conf  # refer file 'mongo-db-config.yaml' and path: metadata -> name
      # reload the changes automatically in given period
      reload:
        enabled: true
        mode: polling
        period: 1000 # every 1 sec
  
# actutor end-points
management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true