apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  # Ye storage rahega kya means Cloud mai or Cluster mai or Local mai
  # Is host configuration pe hume data chahiye
  hostPath:
    # In which path, we will store our data.
    path: /data/
    # Create this path: /data/ if does not exist
    type: DirectoryOrCreate