apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongo-app
  clusterIP: None  # We Use DNS, Thus ClusterIP is not relevant
  ports:
    - name: tcp
      port: 27017
      targetPort: 27017
      

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
        - name: mongo-app
          image: mongo:latest
          ports:
           - containerPort: 27017
             name: mongo-app
          env:
           - name: MONGO_INITDB_ROOT_USERNAME
             valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: username
           - name: MONGO_INITDB_ROOT_PASSWORD
             valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: password
          # we are telling to mongo-db that, mongo-db ko new data-volume ko point krna hai jo hum bna rhe hai.
          volumeMounts:
            # conatiner ke andar ek mongo app run hogi and uske andar ke ek path bna rhe hai : /data/db and is path ko external volume ko point krne ko bol rhe hai jo hum bna rhe hai.
            - mountPath: /data/db # This is the path in the container on which the mounting will take place.
              name: mongo-persistent-storage # volume-name and should be same as below configuration: volumes -> name
      volumes:
        - name: mongo-persistent-storage # Obtaining 'volume' from PVC
          persistentVolumeClaim:
            claimName: mongo-pv-claim  # we are targeting the volumn which we created in file 'host-pvc.yaml' under path : metadata -> name


