apiVersion: v1
kind: Service

metadata:
  name: docker-basic-assignment-service-app-metadata
  labels:
    app: docker-basic-assignment-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30008
  selector:
    app: docker-basic-assignment-app