apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongo-app
  clusterIP: None  # We Use DNS, Thus ClusterIP is not relevant
  ports:
    - name: tcp
      port: 27017
      targetPort: 27017
      

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
        - name: mongo-app
          image: mongo:latest
          ports:
           - containerPort: 27017
             name: mongo-app
          env:
           - name: MONGO_INITDB_ROOT_USERNAME
             valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: username
           - name: MONGO_INITDB_ROOT_PASSWORD
             valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: password
